### ISSUE TITLE
Quanta starts (sort of) but localhost refuses connections

### ISSUE THREAD

**Issue by LilFonky** [Clay-Ferguson/quantizr#38]
Greetings from Denton-

Trying to run the Docker container using the `run-distro.sh` script.  The container lights up but I'm getting some errors, and Quanta is inaccessible via the browser. Terminal output looks like this:

```
root@origin:/home/analytic/quanta/quanta-distro# bash run-distro.sh
Stopping any existing server instance...
curl: (7) Failed to connect to localhost port 8185: Connection refused
dockerDown docker-compose-distro.yaml serivce quanta-distro
No stopped containers
dockerDown docker-compose-distro.yaml serivce mongo-distro
No stopped containers
All down.
removing logs
Generating /home/analytic/quanta/quanta-distro/mongod.conf
docker-compose version 1.25.0, build unknown
dockerUp
ipfs not enabled
Not starting MongoDB
Creating mongo-distro ... done
Creating quanta-distro ... done
Docker Compose: up successful.
d2fd74771552   subnode/repo:quanta1.0.24               "/bin/bash -c /quant…"   Less than a second ago   Up Less than a second   4001/tcp, 4001/udp, 0.0.0.0:8185->8185/tcp, :::8185->8185/tcp                                                                                                                            quanta-distro
quanta-distro started ok
c06c6dec55c4   mongo:4.0                               "docker-entrypoint.s…"   1 second ago   Up Less than a second   27017/tcp, 0.0.0.0:27020->27020/tcp, :::27020->27020/tcp                                                                                                                                 mongo-distro
mongo-distro started ok
================================================
Quanta Started OK!
http://localhost:8185
Login with: UserName=admin, Password=xxxxx
================================================
Press any key.

```
This is probably something connected to my own Docker ignorance, so if there's something I'm overlooking please let me know.  Pretty excited about giving this a whirl.

Cheers,

Taylor

**Comment by Clay-Ferguson** [comment]
So you unzipped the distro zip I guess, and then just ran the script? There should be a log folder in there which might contain some hints. 

Also I'll be updating the docker repository image tonight or tomorrow to get that up to current code, in case the current release out there is broken.

**Comment by LilFonky** [comment]
Yes that's correct, I'll look for the log files, and thanks for the quick reply. If there's anything of interest in there I'll post it here for you and others to look at...

**Comment by LilFonky** [comment]
So I tried 1.0.25 and got the same results.  I took a look at `logback.xml` in the log directory but didn't pick up on any clues. 

I also thought to build the executable myself but wasn't able to locate a /scripts directory, and therefore no `build-distro.sh` script. This makes me think I am probably  just missing something I should be getting.  Here's what I see if I do` ls -a` in the distro directory: 
```

backup.sh  dc-distro-app.yaml    dockerfile               ipfs         run-distro.sh            tmp
branding   dc-distro-ipfs.yaml   dumps                    log          secrets.sh
config     dc-distro-mongo.yaml  entrypoint.sh            mongod.conf  setenv-distro-runner.sh
data       define-functions.sh   gen-mongod-conf-file.sh  restore.sh   stop-distro.sh
```
Should there not be a `/scripts` directory here or am I looking in the wrong place?

Also not really sure this is salient to the issue but the logback file mentions `/src/main/resources/logback-spring.xml` for editing purposes but I can't find this directory. Perhaps even more evidence that either I am out-to-lunch or maybe something is goofy on my machine.

Thanks again!

**Comment by Clay-Ferguson** [comment]
do you see the spring-boot-logger.log file in the log folder ?

also run this: 'docker logs quanta-distro' to view the logs inside the container.

**Comment by Clay-Ferguson** [comment]
Also please run 'docker ps' and let me know the output. thanks.

**Comment by LilFonky** [comment]
Now we're getting somewhere. 

There is in fact no `spring-boot-logger.log` in the log directory

`docker logs quanta-distro` returns:

```
Error: Invalid or corrupt jarfile /quanta/app.jar
```

docker ps returns:

```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED         STATUS                  PORTS                                                                                                                                                                                    NAMES
fd59a2e66ecc   mongo:4.0                               "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes            27017/tcp, 0.0.0.0:27020->27020/tcp, :::27020->27020/tcp                                                                                                                                 mongo-distro
c1db0d447ccc   linuxserver/homeassistant:latest        "/init"                  42 hours ago    Up 42 hours                                                                                                                                                                                                      3cf49a50-9784-405e-88d9-92555f3b00f5
e2a5f9f5e8b3   lscr.io/linuxserver/librespeed:latest   "/init"                  44 hours ago    Up 44 hours             443/tcp, 0.0.0.0:8001->80/tcp, :::8001->80/tcp                                                                                                                                           librespeed
6154f07d9713   selfhostedpro/yacht                     "/init"                  44 hours ago    Up 44 hours             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                                                                quizzical_mendel
d8a2a786b824   linuxserver/jellyfin:latest             "/init"                  45 hours ago    Up 45 hours             0.0.0.0:1900->1900/tcp, :::1900->1900/tcp, 0.0.0.0:7359->7359/tcp, :::7359->7359/tcp, 0.0.0.0:8096->8096/tcp, :::8096->8096/tcp, 0.0.0.0:8920->8920/tcp, :::8920->8920/tcp               0c4eae62-3b4e-4c47-945e-2c7b62a0bd5c
78fe17cdabf6   filebrowser/filebrowser:latest          "/filebrowser"           2 days ago      Up 45 hours (healthy)   0.0.0.0:34843->80/tcp, :::34843->80/tcp                                                                                                                                                  1b24f640-8cc6-43e9-aa86-4305d27d9393
dc9b322ba4c8   linuxserver/syncthing:latest            "/init"                  2 days ago      Up 45 hours             0.0.0.0:8384->8384/tcp, 0.0.0.0:21027->21027/udp, :::8384->8384/tcp, :::21027->21027/udp, 0.0.0.0:22000->22000/tcp, :::22000->22000/tcp, 0.0.0.0:22000->22000/udp, :::22000->22000/udp   3169a6bc-0b41-41d1-a52b-dd536e3c9beb
```
I can see mongo-related stuff but otherwise nothing else that reminds me of Quanta.

**Comment by Clay-Ferguson** [comment]
ok, let's check the image itself, please run both these:

```sh
docker image ls subnode/repo:quanta1.0.25
docker image inspect subnode/repo:quanta1.0.25
```
And post the output. thanks.

**Comment by Clay-Ferguson** [comment]
And what the heck let's compare docker versions too...

```
docker --version
```
I'm on Docker version 20.10.14, build a224086

**Comment by LilFonky** [comment]
Here:

`Docker version 20.10.15, build fd82621`

Here:
```
REPOSITORY     TAG            IMAGE ID       CREATED        SIZE
subnode/repo   quanta1.0.25   7088e74c2427   23 hours ago   307MB
```
and here:
```

[
    {
        "Id": "sha256:7088e74c2427c2aadaea7c92b588a98db257f1d26d560cf02a99d0e8a0d86545",
        "RepoTags": [
            "subnode/repo:quanta1.0.25"
        ],
        "RepoDigests": [],
        "Parent": "sha256:4bb79bc1ab774feb674f32e45715f54dc9f94361b6e735c111d432d987a54403",
        "Comment": "",
        "Created": "2022-05-09T01:10:36.938268039Z",
        "Container": "dd0aeb74732701556a509275b9751f52d2782c1a92ff018a8d4c31955a3335ff",
        "ContainerConfig": {
            "Hostname": "dd0aeb747327",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4001/tcp": {},
                "4001/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/usr/local/openjdk-11",
                "LANG=C.UTF-8",
                "JAVA_VERSION=11.0.15"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/quanta/entrypoint.sh\"]"
            ],
            "Image": "sha256:4bb79bc1ab774feb674f32e45715f54dc9f94361b6e735c111d432d987a54403",
            "Volumes": null,
            "WorkingDir": "/quanta",
            "Entrypoint": [
                "/quanta/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "wclayf@gmail.com"
            }
        },
        "DockerVersion": "20.10.15",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4001/tcp": {},
                "4001/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/usr/local/openjdk-11",
                "LANG=C.UTF-8",
                "JAVA_VERSION=11.0.15"
            ],
            "Cmd": null,
            "Image": "sha256:4bb79bc1ab774feb674f32e45715f54dc9f94361b6e735c111d432d987a54403",
            "Volumes": null,
            "WorkingDir": "/quanta",
            "Entrypoint": [
                "/quanta/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "wclayf@gmail.com"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 306672651,
        "VirtualSize": 306672651,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5baf2890766eaf803fa662f0b9ea6c4363321f1cfbc96498d8c57f2d461f0626/diff:/var/lib/docker/overlay2/3f77958cf5877f42f517712692588f531325871373b230786f8c126174df9e63/diff:/var/lib/docker/overlay2/a6d39085a1f6114f55de5e5fb9938ac5415a5de57cff89bedf7ecff201ce80f0/diff:/var/lib/docker/overlay2/034ce891b01a665b25780b472def446ebc938e9fd0cc1c1f009fbc4c91816df3/diff:/var/lib/docker/overlay2/59bd43820e291244b8f17c51c36a5c8edec41058e09427089483af64bd7cec4d/diff:/var/lib/docker/overlay2/cb339d354d0de764df07c81210a7abdb63bb5b85ae252d16e7b9b21809dc5659/diff:/var/lib/docker/overlay2/fe96c0604c17cb9c097e085a099bfc74419fa86cac15ed9aea06a4d6ab422c10/diff:/var/lib/docker/overlay2/d01ae22d880f90b528df58f2989f33a619f9b00aa58225eb880cee132772c890/diff:/var/lib/docker/overlay2/85e1c78cff5b20822c3a9ec9ac5d848f2de748eb2f9413e91bc3309afdb8bf0b/diff:/var/lib/docker/overlay2/9b8df8ee87bd06e7dccfb8644004704576d02ace65520f39b0978810d673f2c0/diff:/var/lib/docker/overlay2/07ba078cf62ec3463ab025c60577f0b0435cb1423254194c4760744ca7c2f6b0/diff:/var/lib/docker/overlay2/b272d096de5949cf8f492b53647fa0caa5f45ccce909fc05e91d105e6f174563/diff:/var/lib/docker/overlay2/5e8eed1c7db655989336c0a28d056911c7cbc5c39773feab5eacb4736d777414/diff:/var/lib/docker/overlay2/fdfa4099627c571a9e9551b9cac2a57a71257d6e03fa5ee88d7894113d6b6de3/diff",
                "MergedDir": "/var/lib/docker/overlay2/4b76869ec31e1bbfbb5d4c87f245cb8dbe11e047d29a392cd9733e465cbb0f60/merged",
                "UpperDir": "/var/lib/docker/overlay2/4b76869ec31e1bbfbb5d4c87f245cb8dbe11e047d29a392cd9733e465cbb0f60/diff",
                "WorkDir": "/var/lib/docker/overlay2/4b76869ec31e1bbfbb5d4c87f245cb8dbe11e047d29a392cd9733e465cbb0f60/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:a13c519c6361b881ba38a452d05e130fc2ee26f0849f119936d747b96cf6a5c3",
                "sha256:bafdbe68e4aee5999c326aaa33571b595d6bfbea119742439588c3e0c1a56130",
                "sha256:a037458de4e074da622d972e28cfa275c246c684e06efdd28d39c0faa45cb633",
                "sha256:2bfa6a777f318f0861315532b62433ced0eef86b169d914f74e430dc810b140e",
                "sha256:6f2b7a0bafcd530d1bc3f921b15f33e83da3be47cd35fb16a6986a665486f3da",
                "sha256:e69c181cbfd2c1b3e246d9111f2891af36d3d37216bcac527278c4e210303775",
                "sha256:8b38ced9d21348ff53df18b7fcf40e021688d96b93b10dabbe9636563a1bdf7f",
                "sha256:4e515cd07306f257dae27f40fdaba416b4b47fac1627de3f46f4e1d89633b3c6",
                "sha256:79fcb74fdafb374545aa0652e67d678553387e4ec4b6258b92f982e8d4938ac8",
                "sha256:9a3ae7b386421a328dbb6c641da96eff54d24fe032f1b7fad16c99eeaddf0604",
                "sha256:8ef1e63d17785a1992349ca936f87e911233e48571f6c55c68ec7830aef01852",
                "sha256:a4bb39fb00676015ba58c59d76f6dced499c5a68595745f0c59a4f43828cced1",
                "sha256:b633db05a637a384016903f7f68671a4964d1dc38a0f5102700f60f921a8e4da",
                "sha256:2f35c42fcfc4a0db78c747d29fedd60cd68078aaba11b6e2adaa02c157f79ac5",
                "sha256:2f35c42fcfc4a0db78c747d29fedd60cd68078aaba11b6e2adaa02c157f79ac5"
            ]
        },
        "Metadata": {
            "LastTagTime": "2022-05-09T01:10:36.976417332Z"
        }
    }
]
```

**Comment by Clay-Ferguson** [comment]
Your RepoDigests is not showing what it should (afaik):

here's mine, and it matches what hub.docker.com is showing too.
"RepoDigests": [
            "subnode/repo@sha256:1ca37a9439c8967e44784c91a3d4425740e5b5abe9b6e7287dd528933d098d2c"
        ],

maybe you built the code and overwrote something in your local repo? Try deleting it like this to clean it out:

```
docker rmi subnode/repo:quanta1.0.25
```
and then just try running again, it should download from docker repo automatically.

**Comment by Clay-Ferguson** [comment]
BTW, when I verified all this from scratch myself I did notice I had to run with sudo, to get the MongoDb to be able to access it's data folder, so I do need to fix that.

**Comment by LilFonky** [comment]
All-sudo-all-the-time, heretofore.

Still failing, but differently now. After running:

`docker rmi subnode/repo:quanta1.0.25`

and then re-running the `run-distro.sh` script, I get this output:

```
analytic@origin:~/quanta1.0.25/quanta-distro$ sudo ./run-distro.sh
[sudo] password for analytic: 
Stopping any existing server instance...
curl: (7) Failed to connect to localhost port 8185: Connection refused
dockerDown dc-distro-app.yaml serivce quanta-distro
No stopped containers
dockerDown dc-distro-mongo.yaml serivce mongo-distro
Stopping mongo-distro ... done
Going to remove mongo-distro
Removing mongo-distro ... done
dockerDown dc-distro-ipfs.yaml serivce ipfs-distro
WARNING: Some services (ipfs-distro) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
WARNING: Some services (ipfs-distro) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
No stopped containers
All down.
removing logs
Generating /home/analytic/quanta1.0.25/quanta-distro/mongod.conf
docker-compose version 1.25.0, build unknown
dockerUp
ipfs not in use
Creating mongo-distro ... done
MongoDB Compose: up successful.
WARNING: Found orphan containers (mongo-distro) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building quanta-distro
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 366, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1084, in build
    build_output = builder.build(
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 159, in build
    context = utils.tar(
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 29, in tar
    return create_archive(
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 79, in create_archive
    i = t.gettarinfo(full_path, arcname=path)
  File "/usr/lib/python3.8/tarfile.py", line 1834, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/analytic/quanta1.0.25/quanta-distro/data/journal/WiredTigerPreplog.0000000001'
Docker Compose: up failed. EXIT CODE: 1
Press any key to exit.



```

If I again run:

```
sudo docker image ls subnode/repo:quanta1.0.25

```

I now get null output:

```
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

```

So next, I delete the whole dang directory, then re-unzip from the archive, then try to re-run. Still different terminal output, seems vaguely promising:

```
analytic@origin:~/quanta1.0.25/quanta-distro$ sudo bash run-distro.sh
run-distro.sh: line 17: ./stop-distro.sh: Permission denied
removing logs
run-distro.sh: line 31: ./gen-mongod-conf-file.sh: Permission denied
docker-compose version 1.25.0, build unknown
dockerUp
ipfs not in use
Recreating mongo-distro ... done
MongoDB Compose: up successful.
WARNING: Found orphan containers (mongo-distro) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building quanta-distro
Step 1/21 : FROM openjdk:11-jre
 ---> cf646297c902
Step 2/21 : LABEL maintainer="wclayf@gmail.com"
 ---> Using cache
 ---> 8a60f98a21f2
Step 3/21 : ARG PORT
 ---> Using cache
 ---> 23c339aa4ba8
Step 4/21 : ARG PORT_DEBUG
 ---> Using cache
 ---> bbd7f643af65
Step 5/21 : ARG JAR_FILE
 ---> Using cache
 ---> d9fdecdad4c5
Step 6/21 : ARG XMS
 ---> Using cache
 ---> ddcf1eb5c513
Step 7/21 : ARG XMX
 ---> Using cache
 ---> df3f650a471a
Step 8/21 : RUN mkdir -p /dev-resource-base
 ---> Using cache
 ---> 43cd7c286471
Step 9/21 : RUN echo "dummy" > /dev-resource-base/dummy.txt
 ---> Using cache
 ---> cf6c62dc59ff
Step 10/21 : RUN mkdir -p /loader-path
 ---> Using cache
 ---> f2c5d6dd9a1e
Step 11/21 : RUN echo "dummy" > /loader-path/dummy.txt
 ---> Using cache
 ---> 12a66ed3fb9e
Step 12/21 : WORKDIR /quanta
 ---> Using cache
 ---> bf611bb4d5e1
Step 13/21 : EXPOSE ${PORT}
 ---> Using cache
 ---> 49de58f15459
Step 14/21 : EXPOSE ${PORT_DEBUG}
 ---> Using cache
 ---> ad281f622712
Step 15/21 : EXPOSE 4001
 ---> Using cache
 ---> ace4c1d8f91b
Step 16/21 : EXPOSE 4001/udp
 ---> Using cache
 ---> c5018aef49db
Step 17/21 : COPY ${JAR_FILE} /quanta/app.jar
 ---> 42ff36291c0a
Step 18/21 : RUN sh -c 'touch /quanta/app.jar'
 ---> Running in ebaacffb3f5a
Removing intermediate container ebaacffb3f5a
 ---> 263d5c230149
Step 19/21 : COPY ./entrypoint.sh /quanta/entrypoint.sh
 ---> 53c7b604d42d
Step 20/21 : RUN ["chmod", "+x", "/quanta/entrypoint.sh"]
 ---> Running in 9f36d2c2f8e7
Removing intermediate container 9f36d2c2f8e7
 ---> e217f1af85d6
Step 21/21 : ENTRYPOINT ["/quanta/entrypoint.sh"]
 ---> Running in c94bc8241d43
Removing intermediate container c94bc8241d43
 ---> fa69534e91a3

Successfully built fa69534e91a3
Successfully tagged subnode/repo:quanta1.0.25
WARNING: Image for service quanta-distro was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating quanta-distro ... done
Docker Compose: up successful.
cc15442d3872   subnode/repo:quanta1.0.25               "/quanta/entrypoint.…"   1 second ago    Up Less than a second   4001/tcp, 4001/udp, 0.0.0.0:8185->8185/tcp, :::8185->8185/tcp                                                                                                                            quanta-distro
quanta-distro started ok
dc2549564f64   mongo:4.0                               "docker-entrypoint.s…"   6 seconds ago   Up 4 seconds            27017/tcp, 0.0.0.0:27020->27020/tcp, :::27020->27020/tcp                                                                                                                                 mongo-distro
mongo-distro started ok
ipfs not in use
================================================
Quanta Started OK!
http://localhost:8185
================================================
Press any key.
```
Then I re-run:
```
sudo docker image ls subnode/repo:quanta1.0.25

```

and we're back to this:
```
REPOSITORY     TAG            IMAGE ID       CREATED         SIZE
subnode/repo   quanta1.0.25   fa69534e91a3   7 minutes ago   307MB
```
RepoDigests is still showing:

```
"RepoDigests": [],
        "Parent": "sha256:e217f1af85d60d89935212de1575985bca090d29a346eadc4f503d81085cde36"
```

When I try to access the URL in my browser, I momentarily get the self-signed certificate "go away" message before the browser displays "Unable to connect". Not sure this is particularly relevant but you know it's a thing-that's-happening.

**Comment by Clay-Ferguson** [comment]
You're still not getting RepoDigest, and getting errors about things already existing. I think stuff may have just gotten scrambled. 

I'd try this:

* Wipe all your docker images AND containers
* Delete the entire directory you tried to run from
* Unzip quanta1.0.25.tar.gz into a clean folder
* Go into that folder and run 'sudo ./run-distro.sh'

**Comment by LilFonky** [comment]
I think I'm going to requisition a little box, install Ubuntu server onto it with the default Docker roll-in and try it out with literally nothing else going on inside the machine, so it'll just be the OS, Docker, Quanta and maybe a dashboard like Cockpit or something. Might take a few days before I get back onto it. Thanks for sticking with me!

**Comment by Clay-Ferguson** [comment]
It was helpful for me to define these troubleshooting steps too, so this thread has info I'll be adding to a "troubleshooting.md" file in the project (all those commands) so no prob at all.

**Comment by LilFonky** [comment]
Quick update:

I installed Ubuntu sever 20.04 on a clean box with the default docker roll-in (version 20.10.14) and nothing else installed and got all the same results as before - localhost refuses connection, RepoDigests is not coming down as expected, Docker container starts but no actual webpage to log into, etc.

I have since cleaned the images and containers back out of Docker, and my next move will be to try and build the JAR file manually according to the guidance you outlined in install method #2. Will let you know how it goes. Just letting you know before I start in case you're keeping track...

**Comment by Clay-Ferguson** [comment]
I just spun up a brand new Linode instance running Ubuntu 20.04, to test this, and I'm indeed getting the same error you got

```
Error: Invalid or corrupt jarfile /quanta/app.jar
```
Sorry about this, I'm troubleshooting it right now, and hopefully I'll have a solution tonight.

**Comment by Clay-Ferguson** [comment]
Update: After googling this:
```
 docker compose java "Error: Invalid or corrupt jarfile"
```
I see lots of indications this is NOT a jar problem but a path problem. Everyone with this issue seems to be doing what I'm doing which is having a folder that the jar is in. I have a strong hunch if I remove the /quanta folder in the "dockerfile" and just put everything in the root, and make the jar file reference by just "app.jar" that this will fix it. 

I'll let you know. I think this was a docker bug too, but I'm not positive yet.

**Comment by LilFonky** [comment]
Hey thanks for the gumshoe work, I'll be watching this thread!

**Comment by Clay-Ferguson** [comment]
I was glad to get rid of that unnecessary folder, but it had no effect. For some reason docker claims that perfectly good JAR is invalid. I'll look at it more over the weekend. Docker can be REALLY flaky with all the myriad number of ways and syntaxes and formats for that CMD comment. It's always a nightmare touching any of it.

**Comment by LilFonky** [comment]
Thanks for digging into this, hopefully ends up being nothing too odious. Will keep fingers crossed over here...

**Comment by Clay-Ferguson** [comment]
Got it fixed!

It turns out what I was forgetting was to do the Publish to Docker Hub IMMEDIATELY after I build, because if not my local repo gets updated with whatever I happen to be doing as I'm working, and is essentially going to be something random if I come back like a day later and do the publish. When I initially verified my build process works I was of course by chance doing JUST the build+deploy to dockerhub immediately so it always worked.

Other than that I also added instructions to remove the 'build' section from the YAML when not building, just to be safe, and I also deleted the JAR name from the setenv*.sh file, but I'm 95% sure it's the first thing I mentioned above that was making it be broke.

So everything in Github is updated and the 1.0.29 release is on DockerHub. You'll note I updated the distro readme file too, to add this new info, and some troubleshooting steps.

Thanks for your patience and my apologies for the mistake.

**Comment by LilFonky** [comment]
Just fired it up and it's running like a top. Thanks for all your work helping me sort this out!

**Comment by LilFonky** [comment]
Although it might be worth mentioning that your curl test throws the following error:
```
curl: option -H: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information
```
Application works great, test just doesn't like the -H flag.

**Comment by Clay-Ferguson** [comment]
The CURL definitely works on my Linux box (Ubuntu)

```
curl -X POST  http://localhost:8181/mobile/api/ping -H "Accept: application/json" -H 'Content-Type: application/json' -d '{}'
```
I need to fix it where it's consistent with single or double quotes, but other than that it's good. afaik.  Not sure what you were seeing. Anyway, I'll flag this issue as closed. Feel free to contact me at "clay@quanta.wiki" on Fediverse if you want to.
